baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Meditadiones de un cualquiera'
theme = "tale-hugo-master"

[menu]
  [[menu.main]]
    identifier = "contacto"
    name = "contacto"
    title = "contacto"
    url = "/contacto/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0